export type ErrorCode =
  | "MISSING_IMAGE"
  | "NOT_FOUND"
  | "METHOD_NOT_ALLOWED"
  | "UNSUPPORTED_FILE_TYPE"
  | "UNREADABLE_IMAGE"
  | "INVALID_INPUT"
  | "INTERNAL_ERROR";

export const STATUS_BY_CODE: Record<ErrorCode, number> = {
  MISSING_IMAGE: 400,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  UNSUPPORTED_FILE_TYPE: 415,
  UNREADABLE_IMAGE: 422,
  INVALID_INPUT: 400,
  INTERNAL_ERROR: 500,
};
